import {
    ComboBox, VerticalBox, HorizontalBox, GridBox, Button,
    LineEdit, ListView, GroupBox, CheckBox,Slider,TextEdit
} from "std-widgets.slint";


MainWindow := Window {
    min-width: 700px;
    min-height: 400px;
    preferred-width: 700px;
    preferred-height: 400px;
    default-font-size:16px;
    title:"四则运算解释器";
    property <string> re-polish-content <=> re-polish.text;
    property <string> output-content <=> output.text;
    callback input(string);
    GridBox{
        Row{
            Text {
                max-height: 30px;
                preferred-width: 180px;
                text: "四则运算输入:";
                font-weight: 600;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
            HorizontalLayout{
                max-height: 50px;
                InputEdit:= LineEdit {
                    horizontal_stretch: 1;
                    placeholder-text:"请输入表达式！";
                }
            }
            Button {
                text: "解析";
                clicked => {root.input(InputEdit.text) }
            }

        }
        Row{
            Text {
                font-weight: 600;
                text: "逆波兰式:";
                vertical-alignment: top;
                horizontal-alignment: right;
            }
            HorizontalLayout{
                Rectangle {
                    preferred-height: 50px;
                    background: #EFEFEF20;
                        re-polish:= Text {
                            font-size: 14px;
                            text: "";
                            wrap: word-wrap;
                            width: parent.width;
                        }
                }
            }

        }
        Row{
            Text {
                font-weight: 600;
                text: "输出:";
                vertical-alignment: top;
                horizontal-alignment: right;
            }
            HorizontalLayout{
                output:= Text {
                    font-size: 14px;
                    text: "";
                    wrap: word-wrap;
                    horizontal-stretch: 1;
                }
            }
        }
    }
}