import {
    VerticalBox, HorizontalBox, Button,
    LineEdit,ScrollView
} from "std-widgets.slint";

import "FiraCode-Regular.ttf";

MainWindow := Window {
    default-font-family: "Fira Code";
    icon: @image-url("Icon.png");
    min-width: 1000px;
    min-height: 550px;
    preferred-width: 1000px;
    preferred-height: 550px;
    default-font-size: 16px;
    title: "四则运算编译解释器";
    property <string> re-polish-content <=> re-polish.text;
    property <string> output-content <=> output.text;
    property <string> input-content <=> InputEdit.text;
    property input-border-color <=> colormark.color;
    property window-height <=> height;
    property <int>output-width;
    property <int>re-polish-width;
    property out-viewport-x <=> output-view.viewport-x;
    callback input(string);
    VerticalLayout{
        padding: 10px;
        spacing: 10px;
        HorizontalLayout{
            vertical-stretch: 0;
            max-height: 40px;
            spacing: 10px;
            Text {
                width: 120px;
                text: "四则运算输入:";
                font-weight: 600;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
            InputEdit:= LineEdit {
                horizontal_stretch: 1;
                placeholder-text:"请输入表达式！";
                edited => { root.input(InputEdit.text) }
            }
            Button {
                width: 80px;
                text: "解析";
                clicked => {root.input(InputEdit.text) }
            }
        }
        HorizontalLayout{
            vertical-stretch: 0.5;
            spacing: 10px;
            Text {
                width: 120px;
                font-weight: 600;
                text: "逆波兰式:";
                vertical-alignment: top;
                horizontal-alignment: right;
            }
            ScrollView {
                height: {window-height * 0.3};
                width: InputEdit.width;
                viewport-width: re-polish.width;
                border-width: 1px;
                border-radius: 4px;
                border-color: input-border-color;
                HorizontalLayout{
                    padding: 5px;
                    re-polish:= Text {
                        font-size: 14px;
                        text: "";
                        wrap: no-wrap;
                        width: {re-polish-width * 10px};
                    }
                }
            } 
            Rectangle{width: 80px;}
        }
        HorizontalLayout{
            vertical-stretch: 0.7;
            spacing: 10px;
            colormark:= Text {
                width: 120px;
                font-weight: 600;
                text: "输出:";
                vertical-alignment: top;
                horizontal-alignment: right;
            }
            output-view:= ScrollView {
                width: InputEdit.width;
                viewport-width: output.width;
                animate viewport-x {
                    duration: 250ms;
                }
                border-width: 1px;
                border-radius: 4px;
                border-color: input-border-color;
                HorizontalLayout{
                    padding: 5px;
                    output:= Text {
                        width: {output-width * 10px};
                        wrap:no-wrap;
                        font-size: 14px;
                        text: " ";
                    }
                }
            }
            Rectangle{width: 80px;}
        }
        HorizontalLayout{
            vertical-stretch: 0;
            spacing: 10px;
            Rectangle{width: 120px;}
            tip := Text {
                font-size: 14px;
                text: "将负号视为单目运算符处理，支持 '-(2+3)' 和 '(-2)' \n输入中的单目运算符负号 '-' 将以 @ 符号于逆波兰式中表现，以避免和双目运算符减号 '-' 的歧义。\n允许输入科学记数法如 '1e3' '1.9E2' 等。小数可简写为 '.78' ，等价于 '0.78' 。\n内部计算使用精确数 (BigDecimal) 运算而不是浮点数，避免出现浮点错误和 int 溢出。\n运算精度为小数点后 64 位，显示输出精度为小数点后 15 位有效数字。";
                wrap: word-wrap;
                horizontal-stretch: 1;
            }
        }
    }
}